name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        with:
            LBHPACKAGESTONEN: ${{ secrets.LBHPACKAGESTONEN }}
        run: make test
